### ISSUE TITLE
IntelliJ IDEA 14.0: Cannot find configurable: org.codinjutsu.tools.jenkins.JenkinsComponent

### ISSUE THREAD

**Issue by smheaton** [dboissier/jenkins-control-plugin#88]
In in IntelliJ IDEA 14.0, clicking on the "Jenkins Settings" button in he Jenkins pane causes the following exception:

Cannot find configurable: org.codinjutsu.tools.jenkins.JenkinsComponent
java.lang.AssertionError: Cannot find configurable: org.codinjutsu.tools.jenkins.JenkinsComponent
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:130)
	at org.codinjutsu.tools.jenkins.view.action.OpenPluginSettingsAction.showSettingsFor(OpenPluginSettingsAction.java:46)
	at org.codinjutsu.tools.jenkins.view.action.OpenPluginSettingsAction.actionPerformed(OpenPluginSettingsAction.java:42)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:169)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:133)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:312)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by jmkgreen** [comment]
I hit this in the office - makes it look like the plugin is not supported under recent versions of the IDE. Would like to see it fixed properly.

**Comment by olavholten** [comment]
It is only supported up to IntelliJ-13. The whole API seems to have been reworked in IntelliJ-14. 
Looking into it to see whether there is a simple fix. Otherwise it will have to wait, but it's annoying not to see what is going on in Jenkins.

**Comment by dboissier** [comment]
Fixed with the latest version of the plugin

**Comment by oajnath** [comment]
I am still having this issue with the latest version of intelliJ and the jenkins plugin.

**Comment by alexbaumgertner** [comment]
Still reproduce with:

### Runtime
1. WebStorm 2016.1.2
Build #WS-145.971, built on May 1, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
1. Jenkins 0.9.4

### Error
When click on "Jenkins Settings" icon this error occur:
```
AssertionError: Cannot find configurable: org.codinjutsu.tools.jenkins.JenkinsComponent
```

**Comment by Abnaxos** [comment]
Still there in 2016.1.2. Also, there is *no* alternative in the settings.

**Comment by alexbaumgertner** [comment]
@Abnaxos please try the snapshot
https://github.com/dboissier/jenkins-control-plugin/raw/master/snapshot/jenkins-control-plugin-0.9.5-SNAPSHOT-distribution-idea2016.zip

see 
https://github.com/dboissier/jenkins-control-plugin/issues/119#issuecomment-223437018 for more details.

**Comment by Abnaxos** [comment]
@alexbaumgertner The correct URL is https://github.com/dboissier/jenkins-control-plugin/blob/master/snapshot/jenkins-control-plugin-0.9.7-distribution-idea2016.zip, but this one works, thanks.
